### ISSUE TITLE
Continue to difficulty setting after clearing levels

### ISSUE THREAD

**Issue by comradekingu** [Flowit-Game/Flowit#1]
When all levels are cleared, the game asks to pick one of the already played levels instead of landing at the difficulty setting screen.
Would also be nice to have the same checkmark next to the cleared difficulty, like with the levels themselves.

Love this game :)

**Comment by ByteHamster** [comment]
Hmm, I thought it would be more clear to users what is happening when they see the list of levels with checkmarks. Otherwise, it might be unclear why it just jumped out of the level screen.

(also note that you don't have to beat all levels to end up in the last level - beating one unlocks the next 3 levels)

**Comment by comradekingu** [comment]
What if the player is dropped to the difficulty setting screen, and the cleared setting has the checkmark?

**Comment by ByteHamster** [comment]
It doesn't have to be cleared in order to play the last level

(in general, I like the idea of having a "cleared" checkbox next to the difficulty setting screen but having it won't change the situation about what screen to show)

**Comment by ByteHamster** [comment]
I think going back to any other screen than the one you came from would be unexpected for users
