### ISSUE TITLE
[Feature request] Undo button

### ISSUE THREAD

**Issue by nevillepark** [Flowit-Game/Flowit#20]
Hi, I'm really enjoying the game! I think an undo button would be useful, especially for longer or more complicated levels. It can be a little annoying to make a mistake and then try to remember all the steps to solve it from the beginning.

**Comment by comradekingu** [comment]
That is actually a great deal of the challenge with the game.
There is a sense of accomplishment there.
I love Flowit, as it is reminiscent of the earlier age of console/computer game difficulty.

It is one part trying to figure out what to do, and one part figuring out what you have done.
Not only in the current game, but also games before.

If it was possible to just skip back and forwards, that would be ruined.

**Comment by ByteHamster** [comment]
Good point. Without an "undo" button, one has to understand the idea behind the level. With an "undo" button, one can just randomly press buttons until something happens to help

**Comment by joybee** [comment]
Hi, lovely game! I think it absolutely should stay as it is. It's not that bad to strain your working memory a bit. Not everything must be easy. Thanks for creating Flowit!!

**Comment by vertigo220** [comment]
My .02: I initially thought that having an undo would be nice, but then wasn't sure due to the reasons pointed out. Regardless, what people should realize is that just because an undo is added, that doesn't mean one has to use it, and it could even be penalized, either by just counting as another step (so at least 2 steps: one for the mistake and one for the undo). But there are some that enjoy puzzles but maybe don't want or can't handle the added difficulty, and just because some don't want an undo as they want the extra challenge, not having it may result in some not playing or getting as much enjoyment. I see no reason to not at least provide the option for that group of people, and the other group can simply not use it.
