### ISSUE TITLE
Clone of Flowit in react

### ISSUE THREAD

**Issue by HybridAU** [Flowit-Game/Flowit#38]
Hi @ByteHamster and friends,

I've made a clone of Flowit in React / TypeScript. I've been having great fun playing Flowit, and I wanted a project to help me learn a new framework (I'm a python / backend developer).

I've currently got the code in a private repository called "flowit-react" and I'd like to make it public, but I want to do so with your consent. The code I've written is MIT licensed, and the repository doesn't include the levels (as they are GPLv3) but they can be imported from the Levels repository.

I'd be happy to change the name, if you'd prefer I didn't use the "flowit" name, and I could add you to the repository if you would like to at it before I open it up to the world.

Looking forward to hearing back from you,
Michael

**Comment by ByteHamster** [comment]
Hi, nice to hear that you like my game!

I have quite a bad experience with the MIT license in several of my projects, where people took them, transformed them into commercial products and didn't contribute anything back. That's why I'm now using GPL for all my projects. So, personally, I would prefer GPL for Flowit clones as well. Depending on how much you looked at my code, it might even be necessary(?)

> they can be imported from the Levels repository.

How automatic is that process?

If you want, we could move the project to the Flowit organization. We already have a Lua clone there that runs on the PS Vita.

**Comment by HybridAU** [comment]
I'm very happy to change the license to GPLv3 :slightly_smiling_face:. I should be able rebase it so it shows as GPLv3 from the first commit. 

The process to import levels is essentially two steps;  clone the levels repo, then run a script to convert them from xml to typescript files.

```shell
git clone https://github.com/Flowit-Game/Levels.git
yarn convert-levels
```

One thing I'd like to do is setup GitHub actions so that when a commit is tagged, it builds the static files and pushes that to a GitHub pages site, and that could include cloning and converting the levels so it could all be automated. I think that would be fairly easy.

I'd love to move the repository to the Flowit orgaisation :star_struck: I'll add you to the repo I've currently go so you can take a look around.

**Comment by ByteHamster** [comment]
I didn't really think about it earlier, but given that it is a website, how about even AGPLv3? I think the GPL doesn't work too well with websites.

Having it available on GitHub Pages sounds pretty awesome!

**Comment by HybridAU** [comment]
Yeah that makes sense, I've rebased it so it shows as AGPLv3 from the start.

**Comment by HybridAU** [comment]
Thank you so much :) I've created a [repository](https://github.com/Flowit-Game/flowit-react) and set up a workflow so it can be published to https://flowit-game.github.io/flowit-react/

I'm having some issues with the favicon not showing up, but I'll get that worked out soon

**Comment by ByteHamster** [comment]
Nice :) It's cool being able to play the game without having to install anything! I will send the link to my colleague who wanted to play the game on an iPhone :)

Closing this issue because the repo is public now, but feel free to open a new issue or open a discussion in the organization if there is anything else to discuss :)
