### ISSUE TITLE
Wrong optimal moves in medium level 48

### ISSUE THREAD

**Issue by raffaelj** [Flowit-Game/Flowit#43]
Level 48 in medium shows 20 as optimal result, but I solved it with 17 moves.

Version: 4.0 (F-Droid)

PS: I thought about the solver. If you add known, minimal solutions from humans as starting points, you could skip a lot iterations.

PPS: Thanks for this great game. I played the whole collection a few times over the years. With the addition of the optimal solution, the replayability is on another level and I'll have fun for many hours during the next weeks (or months).

**Comment by ByteHamster** [comment]
Huh, I don't know how that happened. Fixed in https://github.com/Flowit-Game/Levels/commit/b261d5c5c8f506acfa137c49866173571d95cbf0

> If you add known, minimal solutions from humans as starting points, you could skip a lot iterations.

That's what I'm already doing for the harder levels. Unfortunately there are some levels where I'm convinced they need, say, 28 moves (very clear and repetitive structure), but the solver already gets stuck at 20 because it does not "see" the structure and cannot prune much. (note that doing 20 first helps to improve pruning at 28)
